CREATE TABLE lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line varchar NULL,
    inserted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);